### ISSUE TITLE
Unparsed HTML in dashboard widget

### ISSUE THREAD

**Issue by glueckpress** [pluginkollektiv/serverstate#6]
The anchor tag in the dashboard widget displays as plain text when no credentials have been entered yet. (WordPress 4.3-RC2-33611)

![image](https://cloud.githubusercontent.com/assets/308422/9255877/6b7368ee-41ec-11e5-861d-b0876c73a250.png)

**Comment by Zodiac1978** [comment]
The reason is: the error message is put out via Javascript:
`<script type='text/javascript'>
/* <![CDATA[ */
var serverstate = {"error":"Bitte Zugangsdaten im Dashboard-Widget <a href=\"http:\/\/testserver.torstenlandsiedel.de\/wp-admin\/?edit=serverstate_dashboard#serverstate_dashboard\">vervollst\u00e4ndigen<\/a>."};
/* ]]> */
</script>`

**Comment by krafit** [comment]
wontfix due to #12
